user_name = input("enter for name")
price = float(input("enter for price"))
print(f"{user_name} bought a pen for ${price}")
fruit_1 = input("enter for fruit_1")
fruit_2 = input("enter for fruit_2")
fruit_3 = input("enter for fruit_3")
price_1 = int(input("enter for price_1"))
price_2 = int(input("enter for price_2"))
price_3 = int(input("enter for price_3"))
print("-"*20)
print(f"{'Item'}:<12 Rs. {'Price':>3}")
print(f"{fruit_1:<12}  Rs.{price_1:>3}")
print(f"{fruit_2:<12}  Rs.{price_2:>3}")
print(f"{fruit_3:<12}  Rs.{price_3:>3}")
year = input("enter for year")
month= input("enter for month")
day = input("enter for day")
print(f"{year}-{month}-{day}")
user_name= input("enter for name")
mark_1 = input("enter for mark_1")
mark_2 = input("enter for mark_2")
mark_3 = input("enter for mark_3")
result = (mark_1+mark_2+mark_3)/3
print(f"Hari scored {result}% in exam")

